---

- hosts: localhost
  become: yes
  vars_files:
    - vars/crafty.yaml
    - vars/minecraft.yaml
  tasks:
    - name: Import Docker keyring
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644
    
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: latest

    - name: Add Docker Compose file
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ default_app_directory}}/docker-compose.yml"