---

- hosts: localhost
  become: yes
  vars_files:
    - ../vars/crafty.yaml
    - ../vars/minecraft.yaml
    - ../vars/vault.yaml
  tasks:
    - name: Import Docker keyring
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644
    
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: latest

    - name: Add Docker Compose file
      ansible.builtin.template:
        src: ../templates/docker-compose.yml.j2
        dest: "{{ default_app_directory }}/docker-compose.yml"

    - name: Add Domeneshop credentials
      ansible.builtin.template:
        src: ../templates/domeneshop_secret.j2
        dest: "{{ default_domeneshop_secret_location  }}"
        mode: 0600

    - name: Install certbot
      ansible.builtin.pip:
        name: "{{ default_certbot_package }}"
        executable: pip3

    - name: Register certbot
      ansible.builtin.shell: |
        certbot certonly \ 
        --agree-tos \
        -- email {{ default_certbot_email }}
        --authenticator dns-domeneshop \
        --dns-domeneshop-credentials {{ default_domeneshop_secret_location  }} \
        --dns-domeneshop-propagation-seconds 120 -d {{ default_certbot_domain }}
      args:
        creates: "/etc/letsencrypt/live/{{ default_certbot_domain }}/cert.pem"

    - name: Add nginx configuration files
      ansible.builtin.template:
        src: ../templates/nginx.conf.j2
        dest: "{{ default_app_directory }}/ngnix.conf"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ default_app_directory }}"